# Helm Chart의 기본 설정값을 정의합니다.
# templates 폴더 안에 있는 yml들이 이 파일에 작성된 값을 참조하여
# k8s 리소스들을 동적으로 생성할 수 있습니다.

# Helm 차트에서 사용할 전역 값들을 정의하는 곳.
# 나중에 생성할 템플릿 파일에 적용할 공통 값을 세팅하는 곳.



image: 886331869898.dkr.ecr.ap-northeast-2.amazonaws.com/config-service:7f4884f7abee1ccf5a7e40c60d7e6f868d2a1000

port: 8888
