apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: {{ .Values.global.replicaCount | default .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    #pod 에 설정되는 컨테이너 설정
    spec:
      imagePullSecrets:
        # values.yaml 파일에 imagePullSecret이라는 데이터가 있다면 실행
        # - name : .(현재 반복중인 항목) | quote(인용부호로 감싸서 적용)
{{/*        {{- if $.Values.imagePullSecrets}}*/}}
{{/*          {{- range $.Values.imagePullSecrets}}*/}}
{{/*        - name: {{ . | quote}}*/}}
{{/*          {{- end}}*/}}
{{/*          {{- end}}*/}}
        - name: ecr-secret
      containers:
        - name: gateway-service-container
          image: {{ .Values.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port}}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.global.env.SPRING_PROFILES_ACTIVE }}"
            - name: SPRING_CLOUD_CONFIG_PROFILE_ACTIVE
              value: "{{ .Values.global.env.SPRING_CLOUD_CONFIG_PROFILE_ACTIVE }}"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "{{ .Values.global.env.SPRING_CLOUD_CONFIG_URI }}"